stages:
  - deploy

before_script:
  - apk add rsync openssh curl
  - echo $CI_CONFIG_JS > ${CI_PROJECT_DIR}/config.js
  - mkdir ${CI_PROJECT_DIR}/scripts
  - echo $CI_MONGO_SCRIPTS > ${CI_PROJECT_DIR}/scripts/mongodb-create-user-roles.js

deploy:
  image: alpine
  stage: deploy
  only:
    - tags
  cache:
    paths:
      - .cache
  script:
    - mkdir -p ~/.ssh
    - echo "$CI_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # -I, --ignore-times don't skip files that match size and time
    - rsync -avI --exclude='.git/' --progress ./ $CI_REMOTE_USERNAME@$CI_REMOTE_HOST:$CI_REMOTE_PATH
    - ssh $CI_REMOTE_USERNAME@$CI_REMOTE_HOST "CI_MONGO_INITDB_ROOT_USERNAME=$CI_MONGO_INITDB_ROOT_USERNAME CI_MONGO_INITDB_ROOT_PASSWORD=$CI_MONGO_INITDB_ROOT_PASSWORD CI_MONGO_INITDB_DATABASE=$CI_MONGO_INITDB_DATABASE cd $CI_REMOTE_PATH && sudo docker-compose up -d --build"
    - curl -s -X POST "https://api.telegram.org/bot$CI_TG_BOT_TOKEN/sendMessage" -d chat_id=$CI_TG_BOT_CHAT_ID -d text="\"yocat2\" $CI_COMMIT_TAG deploy finished."
