version: '3'

services:
  server:
    container_name: yocat2-server
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - yocat2

  mongodb:
    container_name: yocat2-mongodb
    image: mongo:5
    restart: unless-stopped
    command: ['--bind_ip_all']
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - yocat2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CI_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CI_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${CI_MONGO_INITDB_DATABASE}

networks:
  yocat2:
