exports.states = {
  TODO: 'TODO',
  DOWNLOADING: 'DOWNLOADING',
  FAILED_TO_DOWNLOAD: 'FAILED_TO_DOWNLOAD',
  WILL_RECOGNIZE: 'WILL_RECOGNIZE',
  WILL_NOT_RECOGNIZE: 'WILL_NOT_RECOGNIZE',
  RECOGNIZING: 'RECOGNIZING',
  FAILED_TO_RECOGNIZE: 'FAILED_TO_RECOGNIZE',
  WILL_REPOST: 'WILL_REPOST',
  WILL_NOT_REPOST: 'WILL_NOT_REPOST',
  REPOSTING: 'REPOSTING',
  REPOSTED: 'REPOSTED',
  FAILED_TO_REPOST: 'FAILED_TO_REPOST',
}
